// This model represents a plant in the catalog of the application.
import 'package:my_green_space/support_types.dart';

class Plant {

  final String name;          
  final String? description;   
  final String? imageAsset;    
  final List<String> tags;    // Some descriptive tags for the plant.
  final String? exposure;
  final TemperatureRange? temperatureRange; 
  final Period? transplantPeriod;
  final Period? harvestPeriod; 
  final String? irrigation;

  // Only the name of the plant is mandatory. The other fields are optional 
  // and are set to null if not provided.
  Plant({
    required this.name,
    this.description,
    this.imageAsset,
    List<String>? tags,
    this.exposure,
    this.temperatureRange,
    this.transplantPeriod,
    this.harvestPeriod,
    this.irrigation,
  }) : tags = tags ?? []; 

  // Static method that builds the list of plants for the catalog.
  // Informations are taken from 'https://www.ortomio.it/piante-da-orto'.
  static List<Plant> getPlantsCatalog() {
    return [
      Plant(
        name: "Garlic",
        description: "Garlic is a member of the lily family, like onions, leeks, and shallots. It is indispensable in the kitchen and important for health, which is why it should always have a place in the garden. Just a few square meters are enough to grow a year's supply. Thanks to its properties, it can also be used (alone or combined with other products) as a natural repellent against many troublesome garden pests.",
        imageAsset: "images/plants/garlic.jpg",
        tags: ["bulb", "vegetable", "full sun", "low water need", "spring planting", "easy to grow"],
        exposure: "Garlic prefers full sun exposure but can tolerate partial shade for a few hours during the day.",
        temperatureRange: const TemperatureRange(min: 15, max: 25),
        transplantPeriod: Period(start: Month.november, end: Month.march),
        harvestPeriod: Period(start: Month.may, end: Month.june),
        irrigation: "Garlic's water needs depend on soil type, plant stage, temperature, and weather. In dry periods, irrigation is essential to avoid stress. Normally, rainfall is enough, but during dry springs, weekly watering is crucial during bulb swelling (April-June). Avoid overwatering, as garlic is sensitive to waterlogging. Stop watering 15 days before harvest to improve bulb quality and shelf life.",
      ),
      Plant(
        name: "Agretti",
        description: "The Agretto (Salsola soda) is known by many names: Roscano, Frati's beard or Negus beard, and also Lischi or Lischeri. It belongs to the Chenopodiaceae family, like spinach and Swiss chard. It is a typical Mediterranean specialty, very adaptable, and among the most tolerant to salinity and drought. Agretto is still relatively unknown in the kitchen, where it can actually be enjoyed in many ways: it is ideal boiled or quickly sautéed, but can also be eaten raw in mixed salads by those who appreciate its slightly tangy flavor.",
        imageAsset: "images/plants/agretti.jpg",
        tags: ["spring planting", "full sun", "mediterranean", "easy to grow"],
        exposure: "Garlic prefers full sun exposure but can tolerate partial shade for a few hours during the day.",
        temperatureRange: const TemperatureRange(min: 16, max: 25),
        transplantPeriod: Period(start: Month.february, end: Month.june),
        harvestPeriod: Period(start: Month.january, end: Month.december),
        irrigation: "Agretti is a drought-resistant plant that does not tolerate waterlogging. It benefits from some irrigation after transplanting until established, always letting the soil surface dry out first. Afterwards, watering should be minimal. Keep the soil slightly moist before harvest, as water stress can make leaves and stems tougher.",
      ),
      Plant(
        name: "Watermelon",
        description: "Watermelon is a member of the cucumber family, like zucchini, cucumber, melon, and pumpkin. It is a demanding garden plant in terms of space and nutrition, requiring more attention than its 'relatives,' but it can provide great satisfaction. For those wishing to grow watermelon in a pot, the mini watermelon variety is ideal, cultivated vertically on a trellis. The use of grafted plants greatly increases productivity, fruit size, and ease of cultivation.",
        imageAsset: "images/plants/watermelon.jpg",
        tags: ["", ""],
        exposure: "Watermelon requires full sun exposure.",
        temperatureRange: const TemperatureRange(min: 24, max: 30),
        transplantPeriod: Period(start: Month.march, end: Month.june),
        harvestPeriod: Period(start: Month.june, end: Month.september),
        irrigation: "Watermelon needs regular watering throughout its growth, avoiding waterlogging by letting the soil dry on the surface between waterings. Irrigate 2–3 times a week, adjusting based on soil, climate, and plant stage. Water less until flowering, then increase significantly during fruit development (up to 10 liters per plant). Reduce or stop watering a week before harvest to enhance sweetness and prevent cracking.",
      ),
      Plant(
        name: "Asparagus",
        description: "Asparagus belongs to the Liliaceae family, like garlic, onion, shallot, and leek. It is a perennial species that is easy to grow and rewards the initial effort with great satisfaction. It produces valuable spears for many seasons (usually over 10 years), which are harvested in spring. Asparagus alternates between a growing phase—from spring to autumn—and a winter dormancy phase, during which it loses its foliage.",
        imageAsset: "images/plants/asparagus.jpg",
        tags: ["", ""],
        exposure: "Watermelon requires full sun exposure.",
        temperatureRange: const TemperatureRange(min: 18, max: 22),
        transplantPeriod: Period(start: Month.april, end: Month.june),
        harvestPeriod: Period(start: Month.april, end: Month.august),
        irrigation: "Asparagus is very sensitive to waterlogging and needs regular watering after transplanting to establish well, allowing the soil surface to dry between irrigations. In the first summer, water every 2-4 days to avoid stress. During harvest, keep the soil consistently moist for best yield and quality. After harvest, if rainfall is low, water every 3-6 days depending on soil type and temperature (every 3-4 days for sandy soils, 5-6 for clay). In dry summers, continue watering until October, then stop.",
      ),
      Plant(
        name: "Basil",
        description: "Basil is one of the most beloved and widely used Mediterranean plants in cooking. It is easy to grow in the vegetable garden, in the yard, or on a balcony. There are many varieties with different aromas and colors. By understanding its needs, you can have fresh basil available year-round - even in winter, when grown indoors with protection.",
        imageAsset: "images/plants/basil.jpg",
        tags: ["", ""],
        exposure: "Basil prefers full sun exposure, but when temperatures exceed 26°C, it prefers partial shade.",
        temperatureRange: const TemperatureRange(min: 20, max: 25),
        transplantPeriod: Period(start: Month.april, end: Month.june),
        harvestPeriod: Period(start: Month.january, end: Month.december),
        irrigation: "Basil requires frequent watering with small amounts of water. It is crucial to water without wetting the foliage to prevent downy mildew attacks.",
      ),
      Plant(
        name: "Swiss Chard",
        description: "Chards belong to the Chenopodiaceae family, like spinach. They are among the most common leafy vegetables, easy to grow, and available in the garden for most of the year. There are chards varieties with large, fleshy stems and veins, as well as others with smaller, tender leaves, used similarly to spinach. Some are grown for their tasty root and are often confused with turnips.",
        imageAsset: "images/plants/swiss_chard.jpg",
        tags: ["", ""],
        exposure: "Chards prefer full sun exposure but can also adapt to growing in partial shade, which they particularly appreciate during the hotter periods.",
        temperatureRange: const TemperatureRange(min: 15, max: 24),
        transplantPeriod: Period(start: Month.january, end: Month.november),
        harvestPeriod: Period(start: Month.january, end: Month.december),
        irrigation: "Chards require frequent watering with modest amounts of water, keeping the soil consistently moist but without waterlogging (typically 1-2 times a week in cooler periods, and 3-5 times a week in summer).",
      ),
      Plant(
        name: "Artichoke",
        description: "The artichoke belongs to the Composite family, like lettuce, chicory, endive, and cardoons. It is a perennial species that is easy to grow, requires ample space, and can provide great satisfaction, even to beginner gardeners. It begins to produce a few months after transplanting and lives for many years, typically 5-8 years.",
        imageAsset: "images/plants/artichoke.jpg",
        tags: ["", ""],
        exposure: "It prefers full sun exposure.",
        temperatureRange: const TemperatureRange(min: 15, max: 20),
        transplantPeriod: Period(start: Month.march, end: Month.november),
        harvestPeriod: Period(start: Month.february, end: Month.august),
        irrigation: "Artichokes require abundant and regular watering during their full spring production, especially when rainfall is scarce. Water scarcity can affect the quality of the heads. It is important to avoid waterlogging, which is harmful to this plant. For summer transplants aimed at early autumn harvest, frequent watering is crucial for proper establishment. Artichoke plants that have already produced in spring enter a summer dormancy phase, during which they will not be watered until the end of August, when watering will stimulate growth restart.",
      ),
      Plant(
        name: "Carrot",
        description: "Carrot belongs to the Umbelliferae family, like fennel, celery, and parsley. It is a highly loved and widely used vegetable in cooking. When grown in our garden, it is unlikely to produce long, smooth roots like those purchased from the greengrocer, but it will certainly compete with them in flavor!",
        imageAsset: "images/plants/carrot.jpg",
        tags: ["", ""],
        exposure: "Carrots prefer full sun exposure but can adapt to partial shade during the hottest hours of the day in summer.",
        temperatureRange: const TemperatureRange(min: 15, max: 24),
        transplantPeriod: Period(start: Month.february, end: Month.september),
        harvestPeriod: Period(start: Month.april, end: Month.november),
        irrigation: "Carrots require frequent watering in the first few weeks after transplanting, with small amounts of water to keep the soil consistently moist but not waterlogged. Watering is limited during cooler periods. After establishment, water carefully, allowing the soil to dry before watering again to encourage deeper root growth. During the final stage of root swelling, keep the soil cool by watering 1-2 times a week, ensuring the plants neither suffer from water shortage nor waterlogging.",
      ),
      Plant(
        name: "Cardoon",
        description: "The cardoon  is a vegetable harvested in the autumn and winter, closely related to the artichoke, resembling it quite a bit. It belongs to the Composite family, like lettuce, chicory, endive, and artichoke. It is easy to grow and requires ample space to develop fully. The large, fleshy stalks (coste) of this species are used in many recipes for delicious side dishes. The cardoon stalks have different characteristics: the outer stalks are less white and tender and are excellent when cut into small pieces and cooked with tomato sauce, garlic, and sausage; the white middle stalks (those around the central heart) are delicious when boiled and gratinated or fried, while the heart is excellent when eaten raw with dipping sauce.",
        imageAsset: "images/plants/cardoon.jpg",
        tags: ["", ""],
        exposure: "Cardoon prefers full sun exposure.",
        temperatureRange: const TemperatureRange(min: 15, max: 24),
        transplantPeriod: Period(start: Month.may, end: Month.october),
        harvestPeriod: Period(start: Month.october, end: Month.february),
        irrigation: "Cardoon requires regular watering during the summer period.",
      ),
      Plant(
        name: "Cauliflower",
        description: "Cauliflower belongs to the Cruciferae family, like arugula, radish, turnip greens, mizuna, mustard, rapeseed, and all cabbages. It is a typical autumn-winter vegetable but can also be grown in spring. In the kitchen, it can be used both cooked and raw. It can be preserved in vinegar, oil, or frozen.",
        imageAsset: "images/plants/cauliflower.jpg",
        tags: ["", ""],
        exposure: "Cauliflower prefers full sun exposure.",
        temperatureRange: const TemperatureRange(min: 18, max: 25),
        transplantPeriod: Period(start: Month.march, end: Month.april),
        harvestPeriod: Period(start: Month.november, end: Month.january),
        irrigation: "Cauliflower is particularly sensitive to both drought and waterlogging. It prefers frequent watering in the first few weeks after transplanting (typically 2-3 times a week in warmer periods) with moderate amounts to keep the soil moist but without waterlogging. Watering can then be spaced out, with increased quantities (typically 1-2 times a week in cooler periods, 1-3 times a week in summer). During the flower swelling phase, plants should be watered more abundantly to avoid water shortage.",
      ),
      Plant(
        name: "Broccoli",
        description: "Broccoli belong to the Cruciferous family, along with arugula, radish, turnip tops, mizuna, mustard, rapeseed, and all types of cabbage. This vegetable thrives in the autumn-winter season, but some varieties can also be harvested in spring and summer. Broccoli resemble cauliflower but are easier to grow due to their adaptability. Some varieties produce additional side shoots after the main harvest.",
        imageAsset: "images/plants/broccoli.jpg",
        tags: ["", ""],
        exposure: "Broccoli prefer full sun exposure, but they can also grow in partial shade (with at least 6 hours of direct sunlight per day).",
        temperatureRange: const TemperatureRange(min: 20, max: 25),
        transplantPeriod: Period(start: Month.march, end: Month.april),
        harvestPeriod: Period(start: Month.july, end: Month.october),
        irrigation: "Broccoli are sensitive to both drought and waterlogging. They require frequent but moderate watering in the first few weeks after transplanting (about 2-3 times per week during hot weather) to keep the soil moist without creating standing water. Later, watering can be less frequent but more abundant - around 1-2 times per week in cooler weather, and 1-3 times per week in summer. During head formation, plants need more generous watering to avoid water stress.",
      ),
      Plant(
        name: "Chickpea",
        description: "Chickpeas belong to the legume family, along with beans, green beans, fava beans, peas, and many others. Globally, they are an important crop: chickpeas are the third most widely grown legume and, due to their high protein content, can serve as a meat substitute. Like other legumes, they enrich the soil with nitrogen and benefit future crops in the garden, thanks also to their deep root system. Chickpeas are very hardy and easy to grow due to their drought tolerance. They do not require staking or pruning.",
        imageAsset: "images/plants/chickpea.jpg",
        tags: ["", ""],
        exposure: "Chickpeas require full sun exposure.",
        temperatureRange: const TemperatureRange(min: 18, max: 26),
        transplantPeriod: Period(start: Month.march, end: Month.may),
        harvestPeriod: Period(start: Month.june, end: Month.july),
        irrigation: "The chickpea is a plant highly resistant to drought but suffers from waterlogging. It requires some watering after transplanting, until it establishes itself, always waiting for the soil surface to dry out. After that, watering should be very infrequent.",
      ),
      Plant(
        name: "Cucumber",
        description: "Cucumbers belong to the Cucurbitaceae family, along with melon, watermelon, zucchini, pumpkin, and caroselli. In recent years, cucumbers have become increasingly popular, especially due to new high-digestibility varieties that allow even those who can't tolerate traditional varieties to enjoy them. Cucumbers are among the healthiest foods in the summer season. They are one of the few fruiting vegetables that can produce well even with partial shade exposure.",
        imageAsset: "images/plants/cucumber.jpg",
        tags: ["", ""],
        exposure: "The cucumber prefers full sun exposure but can also produce in partial shade (with 6 hours of direct sunlight per day).",
        temperatureRange: const TemperatureRange(min: 20, max: 30),
        transplantPeriod: Period(start: Month.april, end: Month.may),
        harvestPeriod: Period(start: Month.june, end: Month.september),
        irrigation: "Cucumbers need plenty of water but cannot tolerate waterlogging. After transplanting, they require frequent, moderate watering (about 2-3 times per week in hot weather) to keep the soil moist but not soggy. As they grow, watering can become less frequent but more abundant — about 1-2 times per week in cooler periods and 3-5 times per week in summer. From the start of flowering, they should be watered more generously, maintaining consistent soil moisture.",
      ),
      Plant(
        name: "Onion",
        description: "The onion is a bulbous plant of the lily family, like garlic, leek, and shallot. It is one of the most widely used vegetables in cooking and can be available year-round thanks to long-storage varieties.",
        imageAsset: "images/plants/onion.jpg",
        tags: ["", ""],
        exposure: "Onions prefer full sun exposure. In summer, they benefit from light shading during the hottest hours of the day.",
        temperatureRange: const TemperatureRange(min: 10, max: 25),
        transplantPeriod: Period(start: Month.february, end: Month.april),
        harvestPeriod: Period(start: Month.june, end: Month.august),
        irrigation: "Onion water needs vary depending on soil type, plant growth stage, and weather conditions. It's essential to avoid overwatering, as onions are sensitive to waterlogging. In the early stages, they require minimal water—irrigation only as needed every 7-14 days. With regular rainfall, additional watering is usually unnecessary during growth, except in dry conditions. In dry springs and summers, weekly watering is recommended, especially during bulb enlargement, when water demand is highest. Irrigation should be stopped about 15 days before harvest to improve bulb quality and storage.",
      ),
      Plant(
        name: "Chive",
        description: "Chives are a perennial plant of the lily family, related to garlic, leek, and shallot. This flavorful aromatic herb is rich in beneficial properties and widely used in soups, sauces, and mixed salads. It is easy to grow almost anywhere, even in pots, thanks to its adaptability and hardiness.",
        imageAsset: "images/plants/chive.jpg",
        tags: ["", ""],
        exposure: "Full sun exposure for 8 hours a day is ideal, but it also grows well in partial shade.",
        temperatureRange: const TemperatureRange(min: 15, max: 21),
        transplantPeriod: Period(start: Month.february, end: Month.august),
        harvestPeriod: Period(start: Month.april, end: Month.october),
        irrigation: "To grow at its best, it requires moist soil, but it can usually survive on the soil's natural humidity. Watering is important during dry periods and in summer.",
      ),
      Plant(
        name: "Green bean",
        description: "The green bean  belongs to the legume family, along with chickpeas, beans, fava beans, peas, and many others. Although it is typically grown from direct seeding, more and more enthusiasts are successfully growing this legume from seedlings, as it helps avoid issues related to seasonal failures and germination problems, and allows the use of the best varieties available in the professional market.",
        imageAsset: "images/plants/green_bean.jpg",
        tags: ["", ""],
        exposure: "The green bean requires full sun exposure.",
        temperatureRange: const TemperatureRange(min: 17, max: 25),
        transplantPeriod: Period(start: Month.march, end: Month.august),
        harvestPeriod: Period(start: Month.may, end: Month.october),
        irrigation: "The green bean is very sensitive to water shortage and must be watered frequently during hot periods, but with moderate amounts, as it suffers from waterlogging. It is crucial to avoid water stress during the flowering and pod-setting stages.",
      ),
      Plant(
        name: "Bean",
        description: "The bean belongs to the legume family, along with green beans, fava beans, peas, chickpeas, and many others. More and more enthusiasts are successfully growing these legumes by transplanting seedlings, which helps avoid failures due to seasonal issues (or germination problems) and provides access to the best varieties available in the professional market.",
        imageAsset: "images/plants/bean.jpg",
        tags: ["", ""],
        exposure: "The bean requires full sun exposure.",
        temperatureRange: const TemperatureRange(min: 17, max: 25),
        transplantPeriod: Period(start: Month.march, end: Month.june),
        harvestPeriod: Period(start: Month.may, end: Month.september),
        irrigation: "The bean is sensitive to water shortage and must be watered frequently during hot periods, but with moderate amounts, as it suffers from waterlogging. It is crucial to avoid water stress during the flowering and pod-setting stages.",
      ),
      Plant(
        name: "Broad bean",
        description: "Fava beans belong to the legume family, along with chickpeas, beans, green beans, peas, and many others. More and more enthusiasts are successfully growing this legume from seedlings to avoid potential failures caused by seasonal issues and germination problems, and to speed up production. Fava beans are also used when frozen for the winter and in their dried form. Like other species in the family, they enrich the soil with nitrogen.",
        imageAsset: "images/plants/broad_bean.jpg",
        tags: ["", ""],
        exposure: "Fava beans prefer full sun exposure but tolerate partial shade.",
        temperatureRange: const TemperatureRange(min: 15, max: 20),
        transplantPeriod: Period(start: Month.october, end: Month.april),
        harvestPeriod: Period(start: Month.march, end: Month.june),
        irrigation: "Fava beans are sensitive to water shortage and must be watered consistently during hot periods, but with moderate amounts, as they suffer from waterlogging. It is crucial to avoid water stress during the flowering and pod-setting stages. They tolerate light waterlogging more than other legumes, which can reduce production.",
      ),
      Plant(
        name: "Fennel",
        description: "Fennel belongs to the Umbelliferae family, along with carrots, parsley, and celery. It is certainly one of the most beloved and healthiest vegetables for autumn harvesting, and it can also be grown in spring using the suitable varieties. It is a very fascinating plant that, when properly fertilized and watered, provides great satisfaction. Some aspects of its cultivation are considered mysterious (such as pre-flowering or the existence of 'male' and 'female' plants), but they have relatively simple explanations. By carefully following cultivation guidelines, good results can be achieved by anyone.",
        imageAsset: "images/plants/fennel.jpg",
        tags: ["", ""],
        exposure: "Fennel prefers full sun exposure.",
        temperatureRange: const TemperatureRange(min: 15, max: 24),
        transplantPeriod: Period(start: Month.march, end: Month.april),
        harvestPeriod: Period(start: Month.april, end: Month.june),
        irrigation: "Fennel requires very frequent watering, especially in midsummer, but without waterlogging: the soil should dry out slightly on the surface before the next watering. In autumn, watering intervals will be spaced out, but with larger amounts. The soil should be kept cool from the bulb enlargement stage. Water stress encourages pre-flowering.",
      ),
      Plant(
        name: "Strawberry",
        description: "Strawberries belong to the Rosaceae family. They are perennial plants that can be grown both in the garden and in pots on balconies. While strawberry plants can live for 3-5 years, renewing the planting each year results in a much more abundant and higher-quality harvest.",
        imageAsset: "images/plants/strawberry.jpg",
        tags: ["", ""],
        exposure: "Strawberries grow well both in full sun and partial shade.",
        temperatureRange: const TemperatureRange(min: 15, max: 26),
        transplantPeriod: Period(start: Month.january, end: Month.december),
        harvestPeriod: Period(start: Month.may, end: Month.july),
        irrigation: "Strawberries need moderate watering and are particularly sensitive to waterlogging—keep the soil cool but never too wet. Watering usually starts with the appearance of the first flowers, about once a week, and continues until the first white fruits develop. From the first harvest, increase to two waterings per week, gradually raising the amount during the main harvesting period (April-May). In gardens, drip irrigation is ideal—especially with mulching—as it helps prevent excessive moisture on leaves and fruit, reducing disease risk. For summer transplants, frequent but light watering is essential until roots are established. Avoid water stress during flowering and reduce watering during ripening to produce healthier, sweeter fruits.",
      ),
      Plant(
        name: "Lettuce",
        description: "Lettuces belong to the Asteraceae family, like chicories, endives, artichokes, and cardoons. They are the most well-known and widely used salad greens in the world.",
        imageAsset: "images/plants/lettuce.jpg",
        tags: ["", ""],
        exposure: "Lettuce prefers full sun exposure. It tolerates partial shade during the hottest hours of summer days. It can also grow with only 6 hours of direct sunlight, though results are less impressive than in full sun.",
        temperatureRange: const TemperatureRange(min: 15, max: 25),
        transplantPeriod: Period(start: Month.march, end: Month.november),
        harvestPeriod: Period(start: Month.april, end: Month.december),
        irrigation: "Lettuce needs consistently moist soil and frequent watering, without waterlogging. The soil should dry slightly on the surface between irrigations, and plants should not experience drought stress. In spring and autumn, water in the morning 2-4 times per week depending on rainfall. In hot summer months, daily irrigation may be necessary, avoiding the hottest hours. Near harvest time, water only the soil around the base to prevent rot. Once heads are mature, reducing irrigation helps slow bolting, unlike during the growth phase when steady moisture is crucial.",
      ),
      Plant(
        name: "Corn",
        description: "Sweet corn belongs to the grass family. It is a vigorous plant, well-suited to large gardens. Its lush foliage can help reduce wind impact for nearby crops grown at close spacing.",
        imageAsset: "images/plants/corn.jpg",
        tags: ["", ""],
        exposure: "Sweet corn requires full sun exposure.",
        temperatureRange: const TemperatureRange(min: 19, max: 27),
        transplantPeriod: Period(start: Month.march, end: Month.june),
        harvestPeriod: Period(start: Month.august, end: Month.october),
        irrigation: "Corn thrives in areas with frequent summer rainfall. In dry climates, it must be watered consistently during hot periods (avoiding waterlogging), as water stress can cause major issues. Watering should occur at least 2-3 times a week, with larger amounts from the emergence of the tassel (the male flower at the top of the plant) for 3 weeks. Stress during flowering always leads to severe consequences for production.",
      ),
        Plant(
        name: "Eggplant",
        description: "The eggplant is a plant from the nightshade family, like tomatoes, peppers, and potatoes. More demanding in cultivation than tomatoes in terms of nutrition and irrigation, it is one of the most loved summer vegetables, capable of yielding great results. There are many varieties in the range, with different shapes, colors, and flavors: from mild to intense tastes. Grafted eggplant plants significantly increase productivity and ease of cultivation.",
        imageAsset: "images/plants/eggplant.jpg",
        tags: ["", ""],
        exposure: "The eggplant requires full sun exposure. In summer, during the hottest hours of the day, it prefers light shading.",
        temperatureRange: const TemperatureRange(min: 18, max: 26),
        transplantPeriod: Period(start: Month.march, end: Month.june),
        harvestPeriod: Period(start: Month.april, end: Month.august),
        irrigation: "Eggplants require regular watering throughout their growing cycle and need plenty of water during hot periods, but care must be taken not to overwater as they are very sensitive to waterlogging. Watering is done 1-3 times a week in spring, with frequency and quantity depending on soil conditions, plant development, and weather. When the fruit is swelling in summer, more water and more frequent watering (up to 4-5 times a week) are needed. At this stage, the plants must not experience water stress to form a good number of fruits. Insufficient watering can result in small, prematurely aged, and bitter-tasting fruit. Drip irrigation is beneficial for this vegetable.",
      ),
        Plant(
        name: "Cantaloupe",
        description: "Cantaloupe is a cucurbitaceae, like watermelon, zucchini, cucumber, and pumpkin. It is a plant that requires a lot of space and nutrition, needing more attention than zucchini, cucumber, and pumpkin, but it can provide great satisfaction. The use of grafted plants helps to increase productivity and ease of cultivation.",
        imageAsset: "images/plants/cantaloupe.jpg",
        tags: ["", ""],
        exposure: "The cantaloupe requires full sun exposure to produce at its best and achieve the highest quality in terms of sugar content and aroma.",
        temperatureRange: const TemperatureRange(min: 24, max: 30),
        transplantPeriod: Period(start: Month.march, end: Month.june),
        harvestPeriod: Period(start: Month.may, end: Month.september),
        irrigation: "The cantaloupe requires regular watering throughout its growing cycle. It's crucial to avoid waterlogging, allowing the soil to dry on the surface before each watering. Typically, irrigation occurs 1-3 times per week, with frequency and quantity varying based on soil conditions, plant development, and weather. From transplanting to early flowering, watering will be less frequent, waiting until the plants show slight stress before watering again (when some plants begin wilting around noon). Cantaloupes need more water from the start of flowering until fruit enlargement. During these stages, the plants must not experience water stress. If the soil allows, two waterings per week should be more substantial (up to 8-10 liters per plant per irrigation), compared to lighter soils, which require watering 3 times a week. Watering is significantly reduced or stopped 7 days before harvest to enhance the sweetness of the fruit and minimize the risk of cracking.",
      ),
        Plant(
        name: "Chili pepper",
        description: "Among the chili peppers, there are many varieties that are easy to grow, even for beginners, while others have different needs that should be understood and considered. 'Super hot' peppers, in particular, being native to climates very different from ours, require specific care. By respecting their needs, great satisfaction can be achieved even in gardens and vegetable patches at our latitudes. There are chili peppers for all tastes, suitable for various uses, not only in cooking. The garden also offers opportunities to highlight them in beautiful borders; in the vegetable garden, spicy powder can also become a useful tool for pest control.",
        imageAsset: "images/plants/chili_pepper.jpg",
        tags: ["", ""],
        exposure: "Chili peppers prefer full sun exposure but can benefit from partial shade during the day, especially in certain growing conditions.",
        temperatureRange: const TemperatureRange(min: 20, max: 30),
        transplantPeriod: Period(start: Month.march, end: Month.october),
        harvestPeriod: Period(start: Month.january, end: Month.december),
        irrigation: "The water requirements of chili peppers vary depending on the type of soil, the size of the plants, and the weather conditions. It is a species that fears waterlogging, so it is essential to avoid excessive watering while ensuring consistent irrigation to promote balanced growth.",
      ),
        Plant(
        name: "Capsicum",
        description: "The capsicum is a plant from the Solanaceae family, like tomatoes, eggplant, and potatoes. More demanding to cultivate than tomatoes in terms of nutrition and irrigation, it is capable of extending production well into the fall. Among the most important factors for success: proper fertilization, adequate irrigation, and protection during the early stages of development. The variety range includes many different shapes and colors: from mild to intense flavors, with local specialties and high-digestibility peppers for more discerning consumers. Grafted peppers help increase productivity and ease of cultivation, especially in more heavily used soils.",
        imageAsset: "images/plants/capsicum.jpg",
        tags: ["", ""],
        exposure: "The bell pepper requires full sun exposure. In summer, during the hottest hours of the day, it appreciates light shading, starting from mid-June.",
        temperatureRange: const TemperatureRange(min: 16, max: 27),
        transplantPeriod: Period(start: Month.march, end: Month.june),
        harvestPeriod: Period(start: Month.june, end: Month.september),
        irrigation: "The bell pepper requires regular watering throughout its growing cycle and needs a lot of water during hot periods, but excessive watering should be avoided as it is very sensitive to waterlogging. In spring, it is watered 1-3 times per week, with frequency and quantity varying based on soil characteristics, plant development stage, and weather conditions. In summer, more water is required with frequent watering, up to 4-5 times per week (3-5 liters per day). During this phase, the plants should not experience water shortages in order to produce optimally and reduce the risk of apical rot. Insufficient watering can lead to stunted growth, small fruit, and flower drop. Drip irrigation is beneficial for bell peppers.",
      ),
        Plant(
        name: "Pea",
        description: "The pea belongs to the legume family, like beans, broad beans, chickpeas, and many others. More and more enthusiasts are successfully growing these legumes by transplanting seedlings; this way, they avoid failures due to seasonal issues (or germination problems) and gain access to the best varieties available in the professional market.",
        imageAsset: "images/plants/pea.jpg",
        tags: ["", ""],
        exposure: "The pea requires full sun exposure.",
        temperatureRange: const TemperatureRange(min: 10, max: 21),
        transplantPeriod: Period(start: Month.october, end: Month.april),
        harvestPeriod: Period(start: Month.may, end: Month.july),
        irrigation: "The pea is sensitive to water shortage and should be irrigated frequently during hot periods, but with moderate amounts, as it suffers from waterlogging. It is essential to avoid water stress during the flowering and pod-setting stages.",
      ),
        Plant(
        name: "Leek",
        description: "The leek is a member of the lily family, like onion, garlic, shallot, and chives. It is still not well-known in many areas, but is highly appreciated in cooking. It has a milder flavor compared to onion and garlic and is versatile in many uses: from side dishes to soups, and even raw in mixed salads. It is one of the few vegetables available in the garden throughout the winter, thanks to the winter varieties, which are very resistant to frosts.",
        imageAsset: "images/plants/leek.jpg",
        tags: ["", ""],
        exposure: "The leek prefers full sun exposure but tolerates partial shade for a few hours a day. It requires 6-8 hours of direct sunlight per day.",
        temperatureRange: const TemperatureRange(min: 13, max: 24),
        transplantPeriod: Period(start: Month.march, end: Month.september),
        harvestPeriod: Period(start: Month.january, end: Month.december),
        irrigation: "After the first few weeks, depending on external temperatures and soil conditions, leeks may require 1-3 irrigations per week (2-3 in summer). They need consistent watering during dry periods, with weekly irrigation. It's crucial to avoid excess water, as they are sensitive to waterlogging. In the early stages of growth, little water is needed (irrigating only when necessary). In years with regular rainfall, rainwater is usually sufficient during the growing phase, and additional watering is only needed in drought conditions, with water requirements increasing as the plants grow.",
      ),
        Plant(
        name: "Tomato",
        description: "The tomato belongs to the Solanaceae family, like peppers, eggplants, and potatoes. It is one of the most beloved and easy-to-grow vegetables, even for beginners, both in the garden and in pots, thanks to its hardiness and adaptability.",
        imageAsset: "images/plants/tomato.jpg",
        tags: ["", ""],
        exposure: "The tomato requires full sun exposure. In summer, during the hottest hours of the day, it appreciates light shading starting from mid-June.",
        temperatureRange: const TemperatureRange(min: 20, max: 24),
        transplantPeriod: Period(start: Month.march, end: Month.august),
        harvestPeriod: Period(start: Month.may, end: Month.october),
        irrigation: "The tomato is able to survive with limited water supply, but chronic water shortage results in weak plants with a much lower yield compared to the true potential of the varieties. Normally, tomatoes are watered 2-3 times a week in spring: the frequency and amount vary depending on the soil characteristics, the stage of plant development, and the weather conditions. Between waterings, the surface layer of soil around the plants should be allowed to dry out to avoid waterlogging.",
      ),
        Plant(
        name: "Radish",
        description: "The radish belongs to the Cruciferae family, like cabbage, arugula, and turnip greens. It is a very easy-to-grow vegetable and is loved in cooking, often used in crudités and mixed salads. It is among the plants that mature the quickest after transplanting; growing from seedlings, compared to direct sowing in the field, significantly reduces pest attacks from larvae that damage the root, resulting in a high-quality final product. Since the radish can also adapt to semi-shaded positions, requires little space, and is harvestable in a short time, it is one of the best species to use in companion planting.",
        imageAsset: "images/plants/radish.jpg",
        tags: ["", ""],
        exposure: "The radish prefers full sun exposure for at least 6 hours a day, adapting to partial shade during the hottest hours from late spring onwards.",
        temperatureRange: const TemperatureRange(min: 10, max: 18),
        transplantPeriod: Period(start: Month.february, end: Month.may),
        harvestPeriod: Period(start: Month.february, end: Month.june),
        irrigation: "The radish requires frequent watering with moderate amounts, keeping the soil consistently moist but without waterlogging. Water scarcity can lead to a slight spiciness in the roots.",
      ),
        Plant(
        name: "Parsley",
        description: "Parsley belongs to the Umbelliferae family, like fennel, celery, and carrot. It is one of the most commonly used herbs in cooking. The practice of transplanting has become widespread in recent years, proving to be extremely advantageous compared to sowing, as parsley grows very slowly in the field during its early stages and is often difficult. It is also easy to grow in pots. There are more aromatic varieties, like common parsley, and more delicate ones, like curly parsley and Titan. Even root parsley has fragrant leaves that can be used in cooking.",
        imageAsset: "images/plants/parsley.jpg",
        tags: ["", ""],
        exposure: "Parsley prefers exposure from full sun to partial shade. During the hottest hours of the day in summer, it appreciates some shade.",
        temperatureRange: const TemperatureRange(min: 15, max: 22),
        transplantPeriod: Period(start: Month.february, end: Month.october),
        harvestPeriod: Period(start: Month.january, end: Month.december),
        irrigation: "Parsley requires frequent watering in the first few weeks after transplanting, with moderate amounts of water to keep the soil consistently moist but not waterlogged. Watering is limited during cooler periods. After the plants have settled in, water with care, allowing the soil to dry out before the next watering. Both water scarcity and waterlogging should be avoided, as they can lead to root rot.", 
      ),
        Plant(
        name: "Shallot",
        description: "Shallot is a bulbous lily family plant, closely related to onions, like garlic, leeks, and shallots. It has a very strong flavor, making it ideal for uses similar to traditional pungent onions. Its storage life is prolonged, superior to most onions.",
        imageAsset: "images/plants/shallot.jpg",
        tags: ["", ""],
        exposure: "The shallot prefers full sun exposure. In summer, it benefits from light shading during the hottest hours of the day.",
        temperatureRange: const TemperatureRange(min: 10, max: 21),
        transplantPeriod: Period(start: Month.february, end: Month.june),
        harvestPeriod: Period(start: Month.june, end: Month.august),
        irrigation: "The water requirements of shallots vary based on soil characteristics, plant development stage, and climate conditions. It is crucial to avoid excess water, as shallots are sensitive to waterlogging. In the early stages, they require minimal water (irrigating only as needed, every 7-14 days). In years with regular rainfall, rainwater is sufficient during growth, with irrigation needed only during drought periods, as water needs increase with plant size. During dry springs and summers, weekly watering is recommended, especially during bulb swelling when higher water amounts are needed. Watering should be stopped 15 days before harvest to ensure better bulb quality and storage ability.",
      ),
        Plant(
        name: "Spinach",
        description: "Spinach belongs to the Chenopodiaceae family, like beet greens. It is one of the healthiest and most appreciated broad-leaf vegetables, often cooked in dishes alongside beet greens and chicory. Young leaves are ideal for eating raw, to enrich mixed salads.",
        imageAsset: "images/plants/spinach.jpg",
        tags: ["", ""],
        exposure: "Spinach prefers full sun exposure, but it also tolerates cultivation in partial shade during the hottest periods.",
        temperatureRange: const TemperatureRange(min: 15, max: 24),
        transplantPeriod: Period(start: Month.february, end: Month.october),
        harvestPeriod: Period(start: Month.february, end: Month.november),
        irrigation: "Spinach requires frequent watering with moderate amounts to keep the soil consistently moist but without waterlogging (approximately 1-2 times per week during cooler periods, in the absence of rainfall, and 3-4 times per week in summer). Excessive watering causes growth to stall and significant yellowing of the leaves. Water scarcity during summer promotes premature flowering.",
      ),
        Plant(
        name: "Celery",
        description: "Celery belongs to the Umbelliferae family, like fennel, carrot, and parsley. It is one of the most important vegetables in cooking for the flavor it adds to dishes and sauces, as well as for use in pinzimonio. It is an easy plant to grow for its aromatic leaves, but with proper fertilization and irrigation, it can also provide great satisfaction with tender hearts for pinzimonio. In recent years, the cultivation of celeriac, excellent in soups and purees, has become more widespread, offering the aroma of celery even in winter.",
        imageAsset: "images/plants/celery.jpg",
        tags: ["", ""],
        exposure: "Celery prefers full sun exposure, but in summer it doesn't mind some shading during the hottest hours of the day.",
        temperatureRange: const TemperatureRange(min: 15, max: 24),
        transplantPeriod: Period(start: Month.march, end: Month.april),
        harvestPeriod: Period(start: Month.may, end: Month.june),
        irrigation: "Celery requires very frequent watering, especially in midsummer, but without waterlogging: the soil should dry out just on the surface before the next watering. In autumn, watering intervals will be reduced, but with larger quantities.",
      ),
        Plant(
        name: "Valerian",
        description: "Valerian, also known as lamb's lettuce or fat hen, is a compact-growing plant that belongs to the Valerianaceae family. It is one of the most interesting and appreciated vegetables in salads due to the pleasant texture of its leaves and its delicate flavor. It is a very cold-resistant vegetable, suitable for cultivation almost all year round.",
        imageAsset: "images/plants/valerian.jpg",
        tags: ["", ""],
        exposure: "Valerianella prefers full sun exposure, but during the most challenging and hot periods of summer, it prefers partial shade.",
        temperatureRange: const TemperatureRange(min: 10, max: 15),
        transplantPeriod: Period(start: Month.february, end: Month.october),
        harvestPeriod: Period(start: Month.january, end: Month.december),
        irrigation: "Valerianella requires frequent watering with modest amounts, keeping the soil consistently moist but without waterlogging (typically 1-2 times a week during cool but dry periods, and 3-4 times a week in summer).",
      ),
        Plant(
        name: "Pumpkin",
        description: "The pumpkin (Cucurbita maxima, C. moschata) is a member of the cucurbit family, like watermelon, zucchini, cucumber, and melon. It is a plant that requires a lot of space and has relatively low demands in cultivation, being satisfied with balanced fertilization and adequate irrigation during the critical periods of the growth cycle.",
        imageAsset: "images/plants/pumpkin.jpg",
        tags: ["", ""],
        exposure: "Pumpkins require full sun exposure to produce at their best and achieve maximum quality. Some varieties can adapt to partial shade in the summer, during the hottest hours of the day.",
        temperatureRange: const TemperatureRange(min: 23, max: 29),
        transplantPeriod: Period(start: Month.march, end: Month.june),
        harvestPeriod: Period(start: Month.april, end: Month.september),
        irrigation: "The pumpkin has a good tolerance to drought but yields the best results with regular watering during key stages of cultivation. In dry conditions, consistent watering with adequate amounts is necessary, as a lack of water would significantly reduce production and fruit size. It's essential to avoid water stagnation, allowing the soil to dry on the surface before watering. Typically, pumpkins are irrigated 1-2 times per week, with frequency and amounts varying based on soil type, plant development stage, and weather conditions. From transplant to early flowering, the frequency of watering is lower, but more water is needed from the start of flowering until fruit growth. During these phases, plants should not suffer from water shortages to avoid flower drop and fruit abortion. In critical periods, if the soil allows for one weekly irrigation (for clay soils), larger amounts of water should be applied (up to 8-10 liters per plant per watering) compared to lighter soils, where irrigation should occur 2-3 times a week (3-5 liters per plant per watering). Watering should be suspended 10 days before harvest to improve fruit quality.",
      ),
        Plant(
        name: "Zucchini",
        description: "The zucchini is a member of the cucurbit family, like watermelon, melon, pumpkin, and cucumber. It is one of the easiest vegetables to grow, providing great satisfaction even for beginners, thanks to its hardiness and high productivity. Both the fruits, which develop at the base of the female flowers, and the flowers themselves, which are a delicacy in cooking, are used. The young lateral shoots of the plants are also used in well-known recipes in some regions of Italy.",
        imageAsset: "images/plants/zucchini.jpg",
        tags: ["", ""],
        exposure: "The zucchini requires full sun exposure.",
        temperatureRange: const TemperatureRange(min: 23, max: 29),
        transplantPeriod: Period(start: Month.february, end: Month.august),
        harvestPeriod: Period(start: Month.march, end: Month.october),
        irrigation: "Zucchini produce the best results with regular watering during the key stages of cultivation. It is usually watered 1-3 times a week: frequency and quantity vary depending on the soil characteristics, the development stage of the plants, and the weather conditions. Providing too much water in the first 2-3 weeks after transplanting can cause the plants' development to stop. From transplant to the beginning of flowering, watering frequency will be lower, while much more water is required during the fruit production stage.",
      ),
    ];
  } // end getPlantsCatalog() method.
} // end Plant class.